USE uconnect;

INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','San Diego','Hospitality','169');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Harvard University','San Jose','Manufacturing','654');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','San Jose','Transportation','142');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Harvard University','Chicago','Manufacturing','345');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','Dallas','Entertainment','181');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','New York','Technology','899');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','Los Angeles','Education','830');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','Philadelphia','Transportation','520');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Dallas','Hospitality','382');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','San Diego','Manufacturing','863');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','Houston','Healthcare','129');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','Philadelphia','Education','917');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','Chicago','Construction','999');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','San Jose','Retail','952');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','San Antonio','Entertainment','235');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Chicago','Technology','536');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Houston','Hospitality','710');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','Houston','Transportation','217');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','San Jose','Retail','436');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','San Diego','Entertainment','184');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','San Antonio','Hospitality','701');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','Houston','Healthcare','433');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','New York','Entertainment','318');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','San Diego','Manufacturing','238');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Harvard University','San Jose','Retail','760');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Harvard University','San Jose','Healthcare','714');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Dallas','Construction','773');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Fidelity Investments','San Diego','Technology','152');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','San Antonio','Retail','357');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','San Jose','Finance','629');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Wayfair','Dallas','Education','509');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','San Diego','Entertainment','128');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Massachusetts General Hospital','Los Angeles','Transportation','178');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Dallas','Education','158');
INSERT INTO Company(Name,Location,Industry,CompanyID) VALUES ('Boston Consulting Group','Philadelphia','Manufacturing','881');



-- ADDING THE MOCK DATA INTO THE COMPANY RECRUITER
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Hindhaugh','Kain','khindhaugh0@goodreads.com','Hiring Manager',267);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Arkill','Pippa','parkill1@gmpg.org','Hiring Manager',502);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Baal','Cecil','cbaal2@ihg.com','Technical Recruiter',315);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Edon','Carlye','cedon3@github.com','Recruiter',992);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Leebetter','Portia','pleebetter4@google.it','Technical Recruiter',718);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Grigor','Shanan','sgrigor5@mit.edu','Recruiter',571);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Bengochea','Jessy','jbengochea6@imgur.com','Hiring Manager',368);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Diboll','Daniella','ddiboll7@sciencedirect.com','Hiring Manager',326);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Botley','Matty','mbotley8@rediff.com','Hiring Manager',699);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Bau','Forster','fbau9@godaddy.com','Hiring Manager',929);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Branthwaite','Melantha','mbranthwaitea@nationalgeographic.com','Recruiter',125);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Leadbitter','Sher','sleadbitterb@cloudflare.com','Hiring Manager',977);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Pittson','Rhys','rpittsonc@phpbb.com','Recruiter',438);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Fearey','Alida','afeareyd@chronoengine.com','Hiring Manager',201);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Tolcher','Jocko','jtolchere@ycombinator.com','Technical Recruiter',192);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Schneidar','Isidro','ischneidarf@naver.com','Recruiter',650);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Moehler','Fredrick','fmoehlerg@nih.gov','Hiring Manager',524);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Taffs','Noe','ntaffsh@vinaora.com','Recruiter',314);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Wybourne','Aldon','awybournei@apache.org','Hiring Manager',924);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Siemantel','Corry','csiemantelj@patch.com','Technical Recruiter',309);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Knuckles','Dore','dknucklesk@4shared.com','Technical Recruiter',130);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Nassau','Ignatius','inassaul@ifeng.com','Hiring Manager',671);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Reilly','Maighdiln','mreillym@imageshack.us','Recruiter',421);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('McGeraghty','Raina','rmcgeraghtyn@indiegogo.com','Recruiter',588);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Barefoot','Liana','lbarefooto@cpanel.net','Hiring Manager',903);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Kapelhof','Nerte','nkapelhofp@list-manage.com','Hiring Manager',947);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Taw','Paulette','ptawq@narod.ru','Recruiter',983);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Dyshart','Theodosia','tdyshartr@privacy.gov.au','Recruiter',652);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Foxhall','Jillian','jfoxhalls@google.cn','Technical Recruiter',919);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Godwin','Evelin','egodwint@blogspot.com','Hiring Manager',838);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Laraway','Cosme','clarawayu@creativecommons.org','Recruiter',926);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Karlsson','Alysia','akarlssonv@t.co','Recruiter',102);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Monte','Hogan','hmontew@amazon.co.uk','Hiring Manager',216);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Shearme','Sal','sshearmex@multiply.com','Technical Recruiter',258);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Wheelhouse','Anna','awheelhousey@java.com','Hiring Manager',344);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Dobrovsky','Odell','odobrovskyz@abc.net.au','Hiring Manager',870);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Dufty','Daniel','ddufty10@thetimes.co.uk','Technical Recruiter',578);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Probart','Arni','aprobart11@liveinternet.ru','Hiring Manager',787);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('De Fries','Janene','jdefries12@spotify.com','Recruiter',892);
INSERT INTO Company_Recruiter(LastName,FirstName,Email,Position,RecruiterID) VALUES ('Spikins','Melodee','mspikins13@tumblr.com','Recruiter',147);
-- INSERTING THE MOCK DATA INTO Recruiters_List

INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (917,671);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (760,502);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (152,870);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (382,926);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (436,926);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (509,201);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (899,652);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (357,588);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (238,258);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (520,267);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (433,983);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (714,892);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (181,309);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (701,421);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (509,315);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (520,652);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (520,650);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (881,258);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (238,977);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (881,588);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (436,524);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (830,309);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (357,929);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (999,892);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (433,192);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (629,977);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (952,524);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (181,130);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (773,650);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (710,838);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (760,983);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (128,502);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (701,368);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (899,125);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (318,924);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (238,201);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (952,125);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (899,315);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (318,671);
INSERT INTO Recruiters_List(CompanyID,RecruiterID) VALUES (217,147);

-- ADDING THE Position Table Mock Data
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Participated in meetings and presentations',0,7007);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Assisted with research projects',1,6179);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`)VALUES ('Marketing Manager','Assisted with research projects',0,1512);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Analyzed data and created reports',0,4499);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Collaborated with team members on various tasks',0,3432);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Analyzed data and created reports',0,8114);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Developed marketing materials',1,9453);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Developed marketing materials',0,9035);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Marketing Manager','Collaborated with team members on various tasks',0,4316);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Analyzed data and created reports',1,8926);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Analyzed data and created reports',0,8858);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Participated in meetings and presentations',0,6021);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Assisted with research projects',0,2397);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Participated in meetings and presentations',1,3443);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Developed marketing materials',0,9262);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('HR Specialist','Collaborated with team members on various tasks',0,8966);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Assisted with research projects',1,8263);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Marketing Manager','Collaborated with team members on various tasks',1,2708);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Collaborated with team members on various tasks',1,5427);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Collaborated with team members on various tasks',1,3357);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Developed marketing materials',1,5223);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Marketing Manager','Assisted with research projects',1,4982);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Assisted with research projects',0,2359);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Developed marketing materials',1,2226);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Marketing Manager','Analyzed data and created reports',1,8341);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('HR Specialist','Assisted with research projects',0,5778);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('HR Specialist','Analyzed data and created reports',1,6620);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Assisted with research projects',1,5153);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`)VALUES ('Marketing Manager','Developed marketing materials',1,8111);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`)VALUES ('Marketing Manager','Assisted with research projects',1,7621);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Assisted with research projects',1,9745);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`)VALUES ('Sales Associate','Assisted with research projects',1,9776);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Sales Associate','Participated in meetings and presentations',0,6867);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Graphic Designer','Assisted with research projects',0,3847);
INSERT INTO `Position`(`Name`,`Description`,`IsCoop`,`PositionID`) VALUES ('Software Engineer','Analyzed data and created reports',1,6242);
